import { useState } from 'react';
import { useNavigate } from 'react-router-dom';
import { useAuth } from '../context/AuthContext';
import { Lock, Send, Image, Type, AlignLeft, Tag } from 'lucide-react';

const CATEGORIES = [
  { id: 'general', label: 'Genel' },
    { id: 'technology', label: 'Teknoloji' },
      { id: 'business', label: 'Is Dunyasi' },
        { id: 'sports', label: 'Spor' },
          { id: 'gaming', label: 'Gaming' },
            { id: 'hardware', label: 'PC Hardware' },
            ];

            export default function EditorPanel() {
              const { user } = useAuth();
                const navigate = useNavigate();
                  const [form, setForm] = useState({ category: 'general', title: '', imageUrl: '', content: '' });
                    const [status, setStatus] = useState<'idle' | 'loading' | 'success' | 'error'>('idle');
                      const [publishedTitle, setPublishedTitle] = useState('');
                        const [errorMsg, setErrorMsg] = useState('');

                          if (!user) {
                              return (
                                    <div className="min-h-screen bg-gray-950 flex items-center justify-center">
                                            <div className="text-center p-10 bg-gray-900 rounded-2xl border border-gray-800 max-w-sm w-full mx-4">
                                                      <Lock className="w-12 h-12 text-yellow-400 mx-auto mb-4" />
                                                                <h2 className="text-white text-xl font-bold mb-2">Giris Gerekli</h2>
                                                                          <p className="text-gray-400 text-sm mb-6">Editor paneline erismek icin giris yapmaniz gerekiyor.</p>
                                                                                    <button onClick={() => navigate('/login')} className="bg-yellow-500 hover:bg-yellow-400 text-black font-semibold py-2 px-6 rounded-lg transition-colors">
                                                                                                Giris Yap
                                                                                                          </button>
                                                                                                                  </div>
                                                                                                                        </div>
                                                                                                                            );
                                                                                                                              }

                                                                                                                                const authorName = (user as any).displayName || (user as any).email?.split('@')[0] || 'Editor';

                                                                                                                                  const handleChange = (e: React.ChangeEvent<HTMLInputElement | HTMLTextAreaElement | HTMLSelectElement>) => {
                                                                                                                                      setForm(prev => ({ ...prev, [e.target.name]: e.target.value }));
                                                                                                                                        };

                                                                                                                                          const handleSubmit = async (e: React.FormEvent) => {
                                                                                                                                              e.preventDefault();
                                                                                                                                                  if (!form.title.trim() || !form.content.trim()) { setErrorMsg('Baslik ve icerik zorunludur.'); return; }
                                                                                                                                                      setStatus('loading');
                                                                                                                                                          setErrorMsg('');
                                                                                                                                                              try {
                                                                                                                                                                    const res = await fetch('/api/articles', {
                                                                                                                                                                            method: 'POST',
                                                                                                                                                                                    headers: { 'Content-Type': 'application/json' },
                                                                                                                                                                                            body: JSON.stringify({ ...form, author: authorName }),
                                                                                                                                                                                                  });
                                                                                                                                                                                                        if (!res.ok) throw new Error('Hata');
                                                                                                                                                                                                              const data = await res.json();
                                                                                                                                                                                                                    setPublishedTitle(data.article.title);
                                                                                                                                                                                                                          setStatus('success');
                                                                                                                                                                                                                              } catch { setErrorMsg('Haber yayinlanirken hata olustu.'); setStatus('error'); }
                                                                                                                                                                                                                                };

                                                                                                                                                                                                                                  const handleGoToCategory = () => navigate(`/?category=${form.category}`);
                                                                                                                                                                                                                                    const handleReset = () => { setForm({ category: 'general', title: '', imageUrl: '', content: '' }); setStatus('idle'); setPublishedTitle(''); setErrorMsg(''); };

                                                                                                                                                                                                                                      if (status === 'success') {
                                                                                                                                                                                                                                          const catLabel = CATEGORIES.find(c => c.id === form.category)?.label || form.category;
                                                                                                                                                                                                                                              return (
                                                                                                                                                                                                                                                    <div className="min-h-screen bg-gray-950 flex items-center justify-center">
                                                                                                                                                                                                                                                            <div className="text-center p-10 bg-gray-900 rounded-2xl border border-gray-800 max-w-sm w-full mx-4">
                                                                                                                                                                                                                                                                      <div className="w-16 h-16 bg-green-500/20 rounded-full flex items-center justify-center mx-auto mb-4">
                                                                                                                                                                                                                                                                                  <Send className="w-8 h-8 text-green-400" />
                                                                                                                                                                                                                                                                                            </div>
                                                                                                                                                                                                                                                                                                      <h2 className="text-white text-xl font-bold mb-2">Haber Yayinlandi!</h2>
                                                                                                                                                                                                                                                                                                                <p className="text-gray-300 text-sm mb-1">"{publishedTitle}"</p>
                                                                                                                                                                                                                                                                                                                          <p className="text-gray-500 text-sm mb-6"><span className="text-yellow-400 font-medium">{catLabel}</span> bolumunde yayinlandi.</p>
                                                                                                                                                                                                                                                                                                                                    <div className="flex gap-3 justify-center">
                                                                                                                                                                                                                                                                                                                                                <button onClick={handleGoToCategory} className="bg-yellow-500 hover:bg-yellow-400 text-black font-semibold py-2 px-4 rounded-lg text-sm transition-colors">Bolume Git</button>
                                                                                                                                                                                                                                                                                                                                                            <button onClick={handleReset} className="bg-gray-700 hover:bg-gray-600 text-white font-semibold py-2 px-4 rounded-lg text-sm transition-colors">Yeni Haber</button>
                                                                                                                                                                                                                                                                                                                                                                      </div>
                                                                                                                                                                                                                                                                                                                                                                              </div>
                                                                                                                                                                                                                                                                                                                                                                                    </div>
                                                                                                                                                                                                                                                                                                                                                                                        );
                                                                                                                                                                                                                                                                                                                                                                                          }

                                                                                                                                                                                                                                                                                                                                                                                            return (
                                                                                                                                                                                                                                                                                                                                                                                                <div className="min-h-screen bg-gray-950 py-10 px-4">
                                                                                                                                                                                                                                                                                                                                                                                                      <div className="max-w-2xl mx-auto">
                                                                                                                                                                                                                                                                                                                                                                                                              <div className="mb-8">
                                                                                                                                                                                                                                                                                                                                                                                                                        <h1 className="text-2xl font-bold text-white mb-1">Editor Paneli</h1>
                                                                                                                                                                                                                                                                                                                                                                                                                                  <p className="text-gray-400 text-sm">Merhaba, <span className="text-yellow-400">{authorName}</span>. Yeni bir haber yayinla.</p>
                                                                                                                                                                                                                                                                                                                                                                                                                                          </div>
                                                                                                                                                                                                                                                                                                                                                                                                                                                  <form onSubmit={handleSubmit} className="space-y-6">
                                                                                                                                                                                                                                                                                                                                                                                                                                                            <div>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                        <label className="flex items-center gap-2 text-gray-300 text-sm font-medium mb-3"><Tag className="w-4 h-4" /> Bolum</label>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    <div className="grid grid-cols-3 gap-2">
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  {CATEGORIES.map(cat => (
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  <button key={cat.id} type="button" onClick={() => setForm(prev => ({ ...prev, category: cat.id }))}
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    className={`py-2 px-3 rounded-lg text-sm font-medium border transition-colors ${form.category === cat.id ? 'bg-yellow-500 border-yellow-500 text-black' : 'bg-gray-800 border-gray-700 text-gray-300 hover:border-gray-500'}`}>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      {cat.label}
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      </button>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    ))}
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                </div>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          </div>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    <div>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                <label className="flex items-center gap-2 text-gray-300 text-sm font-medium mb-2"><Type className="w-4 h-4" /> Baslik</label>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            <input type="text" name="title" value={form.title} onChange={handleChange} placeholder="Haber basligini girin..." className="w-full bg-gray-800 border border-gray-700 rounded-lg px-4 py-3 text-white placeholder-gray-500 focus:outline-none focus:border-yellow-500 transition-colors" />
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      </div>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                <div>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            <label className="flex items-center gap-2 text-gray-300 text-sm font-medium mb-2"><Image className="w-4 h-4" /> Gorsel URL <span className="text-gray-500 font-normal">(istege bagli)</span></label>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        <input type="url" name="imageUrl" value={form.imageUrl} onChange={handleChange} placeholder="https://..." className="w-full bg-gray-800 border border-gray-700 rounded-lg px-4 py-3 text-white placeholder-gray-500 focus:outline-none focus:border-yellow-500 transition-colors" />
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    {form.imageUrl && <div className="mt-2 rounded-lg overflow-hidden border border-gray-700 h-40"><img src={form.imageUrl} alt="Onizleme" className="w-full h-full object-cover" onError={e => { (e.target as HTMLImageElement).style.display = 'none'; }} /></div>}
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              </div>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        <div>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    <label className="flex items-center gap-2 text-gray-300 text-sm font-medium mb-2"><AlignLeft className="w-4 h-4" /> Haber Icerigi</label>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                <textarea name="content" value={form.content} onChange={handleChange} placeholder="Haber icerigini buraya yazin..." rows={8} className="w-full bg-gray-800 border border-gray-700 rounded-lg px-4 py-3 text-white placeholder-gray-500 focus:outline-none focus:border-yellow-500 transition-colors resize-none" />
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          </div>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    {errorMsg && <p className="text-red-400 text-sm bg-red-400/10 border border-red-400/20 rounded-lg px-4 py-3">{errorMsg}</p>}
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              <button type="submit" disabled={status === 'loading'} className="w-full bg-yellow-500 hover:bg-yellow-400 disabled:opacity-50 disabled:cursor-not-allowed text-black font-bold py-3 px-6 rounded-lg transition-colors flex items-center justify-center gap-2">
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          <Send className="w-4 h-4" />
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      {status === 'loading' ? 'Yayinlaniyor...' : 'Haberi Yayinla'}
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                </button>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        </form>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              </div>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  </div>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    );
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    }